apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: example
  namespace: atest
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: example
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: example
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: example-
      labels:
        build.appstudio.openshift.io/application: example
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: example
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: atest
    spec:
      params:
      - name: git-url
        value: https://github.com/maysunfaisal/multi-components-dockerfile
      - name: output-image
        value: quay.io/redhat-appstudio-qe/test-images-protected:atest-example-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/maysunfaisal/multi-components-dockerfile/main/python-src-docker/Dockerfile
      - name: path-context
        value: python-src-docker
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: example/$(tt.params.git-revision)
    status: {}
status: {}
